---
name: namecheap
on:
  push:
    branches:
      - "main"  
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup qemu
        uses: docker/setup-qemu-action@v2
      - name: setup buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: build the image
        run: |
          docker buildx build \
          --push \
          --tag ${{ secrets.DOCKER_USERNAME }}/namecheap:latest \
          --platform linux/amd64,linux/arm64 . 